services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - redis-network

  api-redis:
    build: .
    container_name: redis-api
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
